import NextTopLoader from 'nextjs-toploader'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className='bg-background'>
        <NextTopLoader color="#0063F3" showSpinner={true} easing="ease" height={6} />

        {children}</body>
    </html>
  )
}
