import Header from "@/components/dasboard-components/header/Header";
import "../globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/dasboard-components/side-bar/SideBar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-start w-full">
          <div className="w-[200px] ">
            <SideBar />
          </div>
          <main className="w-full flex flex-col bg-primary h-screen">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
